# Generated by Django 3.1.1 on 2020-09-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticle', '0002_auto_20200908_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.TextField(default='AP', verbose_name='Author'),
        ),
    ]
