# Generated by Django 3.1.1 on 2020-09-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticle', '0003_auto_20200908_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.TextField(default='news', verbose_name='Icon as per material.io'),
        ),
    ]
