# Generated by Django 3.1.1 on 2020-09-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsarticle', '0005_article_posted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.CharField(default='', max_length=140, verbose_name='Preview to be displayed'),
            preserve_default=False,
        ),
    ]
